image: atlassian/default-image:3

pipelines:
  branches:
    '*':
      - step:
          name: Sync GitHub Mirror
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            # Crear carpeta SSH
            - mkdir -p ~/.ssh

            # Registrar host de Bitbucket
            - ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts

            # Registrar host de GitHub
            - ssh-keyscan github.com >> ~/.ssh/known_hosts

            # Clonar repo origen
            - git clone --bare git@bitbucket.org:camilomardu/backcinepacho.git

            - cd backcinepacho.git

            # Push mirror a GitHub
            - git push --mirror git@github.com:aguapanela-a/CinePacho-Backend.git