image: node:18

clone:
  depth: full

pipelines:
  branches:
    main:
      - step:
          name: Deploy to railway
          caches:
            - node
          script:
            - npm i -g @railway/cli
            - echo "--- REVISANDO ARCHIVOS ---"
            - ls -la
            - echo "--- REVISANDO VARIABLES ---"
            - echo "ID del servicio es [$RAILWAY_SERVICE]"
            - echo "--- INICIANDO DESPLIEGUE ---"
            - railway up --service=$RAILWAY_SERVICE --detach