spring.application.name=demo
server.port=8090

#Para la validación de Enums de entrada y flexibilidad
spring.jackson.datatype.enum.write-enums-to-lowercase=true
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.jackson.datatype.enum.read-unknown-enum-values-as-null=true

# ConfiguraciÃ³n SMTP (ejemplo con Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eribuit9@gmail.com
spring.mail.password=olog kllx pmdh ctds
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL base para el link de confirmaciÃ³n
app.base-url=http://localhost:8081

#conexión a BD
spring.datasource.url=jdbc:postgresql://localhost:5432/CinePacho
spring.datasource.username=postgres
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

