spring.application.name=demo
server.port=${PORT:8010}

#Para la validacion de Enums de entrada y flexibilidad
spring.jackson.datatype.enum.write-enums-to-lowercase=true
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.jackson.datatype.enum.read-unknown-enum-values-as-null=true

## Configuracion SMTP (ejemplo con Gmail)
#spring.mail.host=smtp.gmail.com
#spring.mail.port=465
#spring.mail.username=${GMAIL_USER}
#spring.mail.password=${GMAIL_APP_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.ssl.enable=true
#spring.mail.properties.mail.smtp.starttls.enable=true


brevo.api.key=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

# URL base para el link de confirmacion
app.base-url=${APP_BASE_URL:http://localhost:8010}


#conexion a BD
spring.datasource.url=jdbc:postgresql://localhost:5432/CinePacho
spring.datasource.username=postgres
spring.datasource.password=1407
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#JWT
jwt.secret=${JWT_SECRET: A4NZD6z42ySwrBXUEKPQ52/RCUm5h8k2OqQPGVrOwRM=}
jwt.expiration=${JWT_EXPIRATION_MS:3600000}

#Datos de admin
admin.name=Administrador
admin.email=${ADMIN_EMAIL:admin@cinepacho.com}
admin.password=${ADMIN_PASSWORD:AdminCinePacho123}