spring.application.name=demo
server.port=8010

#Para la validaci�n de Enums de entrada y flexibilidad
spring.jackson.datatype.enum.write-enums-to-lowercase=true
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.jackson.datatype.enum.read-unknown-enum-values-as-null=true

# Configuración SMTP (ejemplo con Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jonathanfelipeochoasilva@gmail.com
spring.mail.password=sybn zbmd bfgu flzl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL base para el link de confirmación
app.base-url=http://localhost:8010

#conexión a BD
spring.datasource.url=jdbc:postgresql://localhost:5432/CinePacho
spring.datasource.username=postgres
spring.datasource.password=1407

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=A4NZD6z42ySwrBXUEKPQ52/RCUm5h8k2OqQPGVrOwRM=
jwt.expiration=3600000

#Datos de admin
admin.name=Administrador
admin.password=AdminCinePacho123
admin.email=admin@cinepacho.com